export const labels = {
  appName: 'ניהול מעשרות ותרומות',
  appShort: 'מעשרות',
  signIn: 'התחברות עם Google',
  signOut: 'התנתקות',
  dashboard: 'לוח בקרה',
  reports: 'דוחות חודשיים',
  fixedDonations: 'תרומות קבועות',
  auditLog: 'יומן פעילות',
  settings: 'הגדרות',
  members: 'חברי משק בית',
  household: 'משק בית',
  createHousehold: 'יצירת משק בית',
  joinHousehold: 'הצטרפות למשק בית',
  householdName: 'שם משק הבית',
  inviteCode: 'קוד הזמנה',
  join: 'הצטרף',
  create: 'צור',
  save: 'שמירה',
  cancel: 'ביטול',
  delete: 'מחיקה',
  edit: 'עריכה',
  export: 'ייצוא',
  exportExcel: 'ייצוא ל-Excel',
  exportCsv: 'ייצוא ל-CSV',
  newReport: 'דוח חודשי חדש',
  month: 'חודש',
  year: 'שנה',
  income: 'הכנסות',
  salaryHusband: 'משכורת בעל',
  salaryWife: 'משכורת אישה',
  additionalIncome: 'הכנסות נוספות',
  totalIncome: 'סה״כ הכנסות',
  maaser: 'מעשר',
  maaserRequired: 'חובת מעשר',
  maaserRemaining: 'יתרת מעשר',
  maaserDebt: 'חוב מעשר',
  maaserCredit: 'זיכוי מעשר',
  openingDebt: 'חוב מעשר פתיחה',
  openingCredit: 'זיכוי מעשר פתיחה',
  closingDebt: 'חוב מעשר סגירה',
  closingCredit: 'זיכוי מעשר סגירה',
  adjustedRequirement: 'חובת מעשר מותאמת',
  fixedDonationsTotal: 'סה״כ תרומות קבועות',
  oneTimeDonations: 'תרומות חד-פעמיות',
  oneTimeDonationsTotal: 'סה״כ תרומות חד-פעמיות',
  remainingBalance: 'יתרה לתשלום',
  description: 'תיאור',
  amount: 'סכום',
  addEntry: 'הוספת רשומה',
  noData: 'אין נתונים להצגה',
  loading: 'טוען...',
  unsavedChanges: 'יש שינויים שלא נשמרו',
  saved: 'נשמר בהצלחה',
  deleted: 'נמחק',
  undo: 'ביטול מחיקה',
  creditCarryForward: 'העברת זיכוי מעשר לחודש הבא',
  creditCarryForwardHint:
    'כאשר מופעל, זיכוי מעשר מחודש קודם מקטין את חובת המעשר בחודש הנוכחי',
  owner: 'בעלים',
  member: 'חבר',
  removeMember: 'הסרת חבר',
  generateInvite: 'יצירת קוד הזמנה',
  copyCode: 'העתקת קוד',
  copied: 'הועתק',
  annualOverview: 'סקירה שנתית',
  filterByMonth: 'סינון לפי חודש',
  filterByUser: 'סינון לפי משתמש',
  allMonths: 'כל החודשים',
  allUsers: 'כל המשתמשים',
  actionCreate: 'יצירה',
  actionUpdate: 'עדכון',
  actionDelete: 'מחיקה',
  startDate: 'תאריך התחלה',
  endDate: 'תאריך סיום',
  active: 'פעיל',
  inactive: 'לא פעיל',
  donationName: 'שם התרומה',
  receipt: 'קבלה',
  uploadReceipt: 'העלאת קבלה',
  selectMonth: 'בחירת חודש',
  previousMonth: 'חודש קודם',
  nextMonth: 'חודש הבא',
  confirmDelete: 'האם למחוק?',
  confirmDeleteDesc: 'פעולה זו תימחק. ניתן לבטל תוך 5 שניות.',
  errorGeneric: 'אירעה שגיאה. נסו שוב.',
  errorAuth: 'שגיאת התחברות. התחברו מחדש.',
  errorPermission: 'אין הרשאה לבצע פעולה זו.',
  errorNotFound: 'הפריט לא נמצא.',
  errorNetwork: 'בעיית רשת. בדקו את החיבור.',
  noHousehold: 'לא נבחר משק בית',
  selectHousehold: 'בחרו או צרו משק בית להמשך',
  welcome: 'ברוכים הבאים',
  shekel: '₪',
  agorotNote: 'כל הסכומים בשקלים',
} as const

export type LabelKey = keyof typeof labels
